include:
  - local: '/common/common.yml'

.npm-qa:
  variables:
    COMMAND: 'npm run test:qa'
  extends:
    - .default
    - .cache-npm
  image: ${NODE_IMAGE}
  script:
    - cd ${WORKING_DIRECTORY}
    - ${COMMAND}
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_REF_NAME == $MAIN_BRANCH
