def add_retry_link
	markdown "**If needed, you can retry the [🔄 `danger-review` job](#{ENV['CI_JOB_URL']}) that generated this comment.**"
end

anything_to_post = status_report.values.any?(&:any?)
if anything_to_post
	add_retry_link()
end