name: NPM Pack

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PACKAGES_DIR: npm-pack-packages
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Pack
        run: |
          mkdir $PACKAGES_DIR
          PACKAGE_TGZ=$(npm pack)
          mv "$PACKAGE_TGZ" $PACKAGES_DIR

      - uses: actions/upload-artifact@v4
        with:
          name: prisma-player-pack
          path: ${{ env.PACKAGES_DIR }}
