include:
  - local: '/common/common.yml'

.npm-unit-test:
  variables:
    COMMAND: 'npm run test:unit'
  extends:
    - .default
    - .cache-npm
  image: ${NODE_IMAGE}
  script:
    - cd ${WORKING_DIRECTORY}
    - ${COMMAND}
  artifacts:
    paths:
      - junit.xml
    reports:
      junit: junit.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_REF_NAME == $MAIN_BRANCH
