include:
  - local: '/common/common.yml'

.create-tag:
  extends:
    - .default
  image: node:22-alpine
  before_script:
    - apk add --no-cache git
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    - VERSION_NUMBER=$(npm pkg get version | xargs echo)
    - git tag $VERSION_NUMBER
    - git remote set-url origin "${CI_SERVER_PROTOCOL}://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/$CI_PROJECT_PATH.git"
    - git push origin $VERSION_NUMBER
  allow_failure: false
  rules:
    - if: $CI_COMMIT_REF_NAME == $MAIN_BRANCH
